In [2]:
"""
# initial guess case: x1, x2 and x3
# v1 = x1
# v2 = x2 - x2x1
# v3 = x3 - x3x2 - x2x1
"""

def compute_vectors(num):
    n = len(num)
    results = []

    for i in range(n):
        if i == 0:
            v = num[i]
        else:
            v = num[i] - sum(num[i] * num[j] for j in range(i))
        results.append(v)

    return results

vector = [1, 2, 3]
r = compute_vectors(vector)
print(r)

[1, 0, -6]


In [3]:
"""
Gram-Schmidt method to perform orthonomal basis given N vectors
Eg. v1 = (1, 2, 2) v2 = (-1, 0, 2) v3 = (0, 0, 1)
"""
import numpy as np

def gram_schmidt(vectors):
    basis = []
    for v in vectors:
        # Orthogonalize
        for b in basis:
            v = v - np.dot(v, b) * b
        # Normalize
        v = v / np.linalg.norm(v)
        basis.append(v)
    return basis

# Example vectors
# v1 = np.array([1, 2, 2])
# v2 = np.array([-1, 0, 2])
# v3 = np.array([0, 0, 1])

v1 = np.array([2, -5, 1])
v2 = np.array([4, -1, 2])


# vectors = [v1, v2, v3]
vectors = [v1, v2]

# Compute orthonormal basis
orthonormal_basis = gram_schmidt(vectors)

# Print the result
for i, vec in enumerate(orthonormal_basis, 1):
    print(f"Orthonormal vector {i}: {vec}")


Orthonormal vector 1: [ 0.36514837 -0.91287093  0.18257419]
Orthonormal vector 2: [0.81649658 0.40824829 0.40824829]


In [6]:
import numpy as np
from scipy.linalg import qr

v1 = np.array([2, -5, 1])
v2 = np.array([4, -1, 2])

# Stack vectors into a matrix
matrix = np.column_stack([v1, v2])

# Perform QR decomposition (Q contains the orthonormal vectors)
Q, R = qr(matrix)

# Print the orthonormal basis
print("Orthonormal basis (Q):")
print(Q)



Orthonormal basis (Q):
[[-3.65148372e-01 -8.16496581e-01 -4.47213595e-01]
 [ 9.12870929e-01 -4.08248290e-01  1.11022302e-16]
 [-1.82574186e-01 -4.08248290e-01  8.94427191e-01]]


In [5]:
import numpy as np

def gram_schmidt(vectors):
    basis = []
    for v in vectors:
        # Orthogonalize
        for b in basis:
            v = v - np.dot(v, b) * b
        # Normalize
        norm = np.linalg.norm(v)
        if norm > 1e-10:  # Avoid division by zero
            v = v / norm
            basis.append(v)
    return basis

# Example vectors
v1 = np.array([2, -5, 1])
v2 = np.array([4, -1, 2])

vectors = [v1, v2]

# Compute orthonormal basis
orthonormal_basis = gram_schmidt(vectors)

# Print the result
for i, vec in enumerate(orthonormal_basis, 1):
    print(f"Orthonormal vector {i}: {vec}")


Orthonormal vector 1: [ 0.36514837 -0.91287093  0.18257419]
Orthonormal vector 2: [0.81649658 0.40824829 0.40824829]


In [7]:
import numpy as np
from scipy.linalg import qr

# Your vectors
v1 = np.array([2, -5, 1])
v2 = np.array([4, -1, 2])

# Gram-Schmidt process
def gram_schmidt(vectors):
    basis = []
    for v in vectors:
        for b in basis:
            v = v - np.dot(v, b) * b
        norm = np.linalg.norm(v)
        if norm > 1e-10:
            v = v / norm
            basis.append(v)
    return basis

vectors = [v1, v2]
gs_basis = gram_schmidt(vectors)

# QR decomposition
matrix = np.column_stack([v1, v2])
Q, R = qr(matrix)

# Print results
print("Gram-Schmidt Orthonormal Basis:")
for vec in gs_basis:
    print(vec)

print("\nQR Decomposition Orthonormal Basis (Q):")
print(Q)

# Check orthonormality
def check_orthonormality(basis):
    for i in range(len(basis)):
        for j in range(i, len(basis)):
            dot_product = np.dot(basis[i], basis[j])
            if i == j:
                print(f"Norm of vector {i+1}: {dot_product}")
            else:
                print(f"Dot product of vector {i+1} and vector {j+1}: {dot_product}")

print("\nChecking Orthonormality of Gram-Schmidt Basis:")
check_orthonormality(gs_basis)

print("\nChecking Orthonormality of QR Basis:")
check_orthonormality(Q)


Gram-Schmidt Orthonormal Basis:
[ 0.36514837 -0.91287093  0.18257419]
[0.81649658 0.40824829 0.40824829]

QR Decomposition Orthonormal Basis (Q):
[[-3.65148372e-01 -8.16496581e-01 -4.47213595e-01]
 [ 9.12870929e-01 -4.08248290e-01  1.11022302e-16]
 [-1.82574186e-01 -4.08248290e-01  8.94427191e-01]]

Checking Orthonormality of Gram-Schmidt Basis:
Norm of vector 1: 1.0
Dot product of vector 1 and vector 2: -5.551115123125783e-17
Norm of vector 2: 0.9999999999999999

Checking Orthonormality of QR Basis:
Norm of vector 1: 1.0000000000000002
Dot product of vector 1 and vector 2: -1.0516183429620329e-16
Dot product of vector 1 and vector 3: 0.0
Norm of vector 2: 1.0000000000000002
Dot product of vector 2 and vector 3: 1.6034639283004177e-17
Norm of vector 3: 1.0


In [8]:
import numpy as np
from scipy.linalg import qr

v1 = np.array([2, -5, 1])
v2 = np.array([4, -1, 2])

# Stack vectors into a matrix
matrix = np.column_stack([v1, v2])

# Perform QR decomposition (Q contains the orthonormal vectors)
Q, R = qr(matrix, mode='economic')

# Print the orthonormal basis
print("Orthonormal basis (Q):")
print(Q)

Orthonormal basis (Q):
[[-0.36514837 -0.81649658]
 [ 0.91287093 -0.40824829]
 [-0.18257419 -0.40824829]]
